{{- if .Values.cloudflared.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    {{- include "waiver-app.labels" . | nindent 4 }}
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- $pullSecrets := include "waiver-app.imagePullSecrets" . }}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- $pullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: cloudflared
          image: "{{ .Values.cloudflared.image.repository }}:{{ .Values.cloudflared.image.tag }}"
          imagePullPolicy: {{ .Values.cloudflared.image.pullPolicy }}
          args:
            {{- toYaml .Values.cloudflared.command | nindent 12 }}
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudflared.tokenSecret.name }}
                  key: {{ .Values.cloudflared.tokenSecret.key }}
          resources:
            {{- toYaml .Values.cloudflared.resources | nindent 12 }}
{{- end }}
