{{- if and .Values.cloudflared.enabled .Values.cloudflared.tokenSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflared.tokenSecret.name }}
  labels:
    {{- include "waiver-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cloudflared.tokenSecret.key }}: {{ .Values.cloudflared.tokenSecret.token | quote }}
{{- end }}
